config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get    '/contact',        to:  'static_pages#contact'
  post   '/users/new',      to:  'users#create'
  get    '/terms',          to:  'static_pages#terms'
  get    '/privacy',        to:  'static_pages#privacy'
  get    '/login',          to:  'sessions#new'
  post   '/login',          to:  'sessions#create'
  delete '/logout',         to:  'sessions#destroy'
  get    '/users/:id/show_detail',          to:  'users#show_detail', as: 'user_show_detail'
  post   '/users/:id/act_histories/new',    to:  'activity_histories#create'
  get    '/users/:id/act_histories',        to:  'activity_histories#show'
  patch  '/users/:id/act_history',          to:  'activity_histories#update'
  delete '/users/:id/act_history',          to:  'activity_histories#destroy'
  post   '/users/:id/act_history/edit',     to:  'activity_histories#edit'
  resources :users
end

app/models/user.rb
class User < ApplicationRecord
  # アクセサ
  attr_accessor :remember_token
  # リレーション
  has_many :activity_historys, dependent: :destroy
  # バリデーション
  validates :name, presence: true, uniqueness: true, length: { maximum: 50 },
   format: { with: /\A[a-zA-Z0-9]+\z/ }
  validates :password, presence: true, length: { minimum: 8 }
  validates :age_birth_checkflg, presence: true
  validates :gender, inclusion: { in: ["0", "1", "2", "9"] }
  validates :age, presence: true, format: { with: /\A[0-9]+\z/ },
    if: Proc.new { |a| a.age_birth_checkflg?("1") }
  with_options if: Proc.new { |a| a.age_birth_checkflg?("0") } do
    validates :birth_date, presence: true
    validate :check_date
  end

  # パスワード認証用
  has_secure_password

  class << self
    # 渡された文字列のハッシュ値を返す
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    # ランダムなトークンを返す
    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  # 永続セッション用トークンをDBに保存する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # 渡されたトークンがダイジェストと一致したらtrueを返す
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # 永続セッション用ユーザーのログイン情報を破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end

  # age_birth_checkflgの値と引数を比較する。
  def age_birth_checkflg?(param)
    param == age_birth_checkflg ? true : false
  end

  private

  def check_date
    return false if birth_date.blank?
    if birth_date >= Date.today
      errors.add(:birth_date, "生年月日は今日より過去である必要があります。")
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: %i[index show]

  def index
    @users = User.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "#{@user.name}さん ようこそ！"
      redirect_to user_path(@user.id)
    else
      render "new"
    end
  end

  def show
    @user = User.find(params[:id])
  end

  def show_detail
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    redirect_to(root_path) unless accessed_user_logged_in?(@user)
  end

  def update
    @user = User.find(params[:id])
    redirect_to(root_path) unless accessed_user_logged_in?(@user)

    if @user.update_attributes(user_params)
      flash[:success] = "ユーザー情報を更新しました！"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    user = User.find(params[:id])
    redirect_to(root_path) unless accessed_user_logged_in?(user)
    user.destroy
    flash[:success] = "ユーザーを削除しました。"
    redirect_to root_path
  end

  private

  def user_params
    params.require(:user).permit(:name, :password, :password_confirmation,
      "birth_date(1i)", "birth_date(2i)", "birth_date(3i)",
      :age_birth_checkflg, :age, :gender, :employment, :hobby, :remarks)
  end

  # ユーザーのログインを確認する
  def logged_in_user
    unless logged_in?
      flash[:danger] = "ログインしてください"
      redirect_to login_path
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_edit.html.erb
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title">ユーザー情報詳細</h4>
      </div>

      <%= form_for(@user, remote: true, html: { class: "modal-body" } )do |f| %>
        <div class="container">
          <div class="row">
            <div class="col-md-2">
              <%= f.label :name %>
            </div>
            <div class="col-md-5">
              <%= f.text_field :name, class: "form-control input-sm ime-active", readonly: true %>
            </div>
          </div>
          <div class="row">
            <div class="col-md-2">
              <%= f.label :age %>
            </div>
            <div class="col-md-5">
              <%= f.text_field :age, class: "form-control input-sm ime-active", readonly: true %>
            </div>
          </div>
          <div class="row">
            <div class="col-md-2">
              <%= f.label :gender %>
            </div>
            <div class="col-md-5">
              <%= f.text_field :gender, class: "form-control input-sm ime-active", readonly: true %>
            </div>
          </div>
          <div class="row">
            <div class="col-md-2">
              <%= f.label :employment %>
            </div>
            <div class="col-md-5">
              <%= f.text_area :employment, class: "form-control input-sm ime-active", readonly: true %>
            </div>
          </div>
          <div class="row">
            <div class="col-md-2">
              <%= f.label :hobby %>
            </div>
            <div class="col-md-5">
              <%= f.text_area :hobby, class: "form-control input-sm ime-active", readonly: true %>
            </div>
          </div>
          <div class="row">
            <div class="col-md-2">
              <%= f.label :remarks %>
            </div>
            <div class="col-md-5">
              <%= f.text_area :remarks, class: "form-control input-sm ime-active", readonly: true %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>

app/views/users/_form.html.erb
<%= form_for(@user, url: yield(:url)) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :name %>
  <p>※ニックネームをご記入下さい。</p>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :password %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class: "form-control" %>

  <%= f.label :age_birth_checkflg %>
  <div>
    <div>
      <label class="radio-inline">
        <%= f.radio_button :age_birth_checkflg, "0" %>生年月日を登録
      </label>
    </div>
    <div>
      <label class="radio-inline">
        <%= f.radio_button :age_birth_checkflg, "1" %>年齢を登録
      </label>
    </div>
    <div>
      <label class="radio-inline radio-buttom">
        <%= f.radio_button :age_birth_checkflg, "2" %>生年月日・年齢どちらも登録しない
      </label>
    </div>
  </div>

  <%= f.label :birth_date %>
  <div>
    <%= f.date_select :birth_date, options = {
      use_month_numbers: true,
      date_separator: "/",
      start_year: 1920,
      end_year: Time.current.year,
      include_blank: true
    }, class: "date-select" %>
  </div>

  <%= f.label :age %>
  <div>
    <%= f.number_field :age, in: 1.0..100.0, step: 1, class: "form-control"  %>
  </div>

  <%= f.label :gender %>
  <div>
    <%= f.select :gender, [["回答しない", "0"], ["男", "1"], ["女", "2"], ["その他", "9"]] %>
  </div>

  <%= f.label :employment %>
  <%= f.text_area :employment, class: "form-control" %>

  <%= f.label :hobby %>
  <%= f.text_area :hobby, class: "form-control" %>

  <%= f.label :remarks %>
  <%= f.text_area :remarks, class: "form-control" %>

  <%= f.submit yield(:button_text), class: "btn btn-primary" %>
<% end %>

<script type="text/javascript">
  $(function(){
     $("input[name=user\\[age_birth_checkflg\\]]:radio").change(function() {
        var radioval = $(this).val();

        var birth_date_obj1 = document.getElementById("user_birth_date_1i");
        var birth_date_obj2 = document.getElementById("user_birth_date_2i");
        var birth_date_obj3 = document.getElementById("user_birth_date_3i");

        switch (radioval) {
          case "0":
            birth_date_obj1.disabled = false;
            birth_date_obj2.disabled = false;
            birth_date_obj3.disabled = false;
            $("input#user_age").prop('disabled', true);
            $("#user_age").val("");
            break;
          case "1":
            birth_date_obj1.disabled = true;
            birth_date_obj2.disabled = true;
            birth_date_obj3.disabled = true;
            $("input#user_age").prop('disabled', false);
            $("#user_birth_date_1i").val("");
            $("#user_birth_date_2i").val("");
            $("#user_birth_date_3i").val("");
            break;
          case "2":
            birth_date_obj1.disabled = true;
            birth_date_obj2.disabled = true;
            birth_date_obj3.disabled = true;
            $("input#user_age").prop('disabled', true);
            $("#user_birth_date_1i").val("");
            $("#user_birth_date_2i").val("");
            $("#user_birth_date_3i").val("");
            $("#user_age").val("");
            break;
        }
     });
  });
</script>

app/views/users/_user_modal.html.erb
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
      <h4 class="modal-title">ユーザー情報詳細</h4>
    </div>
    <%= form_for(@user, remote: true, html: { class: "modal-body" } )do |f| %>

      <% case @user.gender %>
        <% when "0" %>
          <% gender_name = "回答しない" %>
        <% when "1" %>
          <% gender_name = "男" %>
        <% when "2" %>
          <% gender_name = "女" %>
        <% when "9" %>
          <% gender_name = "その他" %>
      <% end %>

      <% case @user.age_birth_checkflg %>
        <% when "0" %>
          <% age_float = ((Time.now - Time.parse(@user.birth_date.to_s)) / 60 / 60 / 24) / 365 %>
          <% calc_age = BigDecimal(age_float.to_s).floor %>
        <% when "1" %>
         <% calc_age = @user.age %>
        <% when "2" %>
          <% calc_age = "" %>
      <% end %>

      <div class="container">
        <div class="row">
          <div class="col-md-2">
            <%= f.label :name %>
          </div>
          <div class="col-md-5">
            <%= f.text_field :name, class: "form-control input-sm ime-active", readonly: true %>
          </div>
        </div>
        <div class="row">
          <div class="col-md-2">
            <%= f.label :age %>
          </div>
          <div class="col-md-5">
            <%= f.text_field :age, value: calc_age, class: "form-control input-sm ime-active", readonly: true %>
          </div>
        </div>
        <div class="row">
          <div class="col-md-2">
            <%= f.label :gender %>
          </div>
          <div class="col-md-5">
            <%= f.text_field :gender, value: gender_name, class: "form-control input-sm ime-active", readonly: true %>
          </div>
        </div>
        <div class="row">
          <div class="col-md-2">
            <%= f.label :employment %>
          </div>
          <div class="col-md-5">
            <%= f.text_area :employment, class: "form-control input-sm ime-active", readonly: true %>
          </div>
        </div>
        <div class="row">
        <div class="col-md-2">
          <%= f.label :hobby %>
        </div>
        <div class="col-md-5">
          <%= f.text_area :hobby, class: "form-control input-sm ime-active", readonly: true %>
        </div>
      </div>
      <div class="row">
        <div class="col-md-2">
          <%= f.label :remarks %>
        </div>
        <div class="col-md-5">
          <%= f.text_area :remarks, class: "form-control input-sm ime-active", readonly: true %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<% provide(:title, 'ユーザー情報変更') %>
<% provide(:url, user_path) %>
<% provide(:button_text, 'ユーザ情報を更新する') %>
<div class="wrapper">
  <h1>ユーザー新規変更</h1>
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <%= render 'form' %>
      <%= link_to "ユーザーを削除しますか？", @user, method: :delete,
                                  data: { confirm: "本当にユーザーを削除しますか？削除されたデータは元に戻りません。" } %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'ユーザー一覧') %>

<div class="wrapper">
  <div class="container">
    <h1>ユーザー一覧</h1>

    <%= will_paginate :previous_label => "&lt&lt", :next_label => '&gt&gt' %>

    <ul class="users">
      <% @users.each do |user| %>
        <li>
          <%= link_to user.name, user %>
          <%= link_to user_show_detail_path(user), remote: true do %>
            <i class="fas fa-info-circle"></i>
          <% end %>
        </li>
      <% end %>
    </ul>

    <div id="user-modal" class="modal fade" tabindex="-1"></div>

    <%= will_paginate :previous_label => "&lt&lt", :next_label => "&gt&gt"%>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, 'ユーザー新規登録') %>
<% provide(:url, new_user_path) %>
<% provide(:button_text, '利用規約に同意の上、ユーザを作成する') %>
<div class="wrapper">
  <h1>ユーザー新規登録</h1>
  <div class="row">
    <div class="col-md-4 col-md-offset-4">
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<div class="container">
  <%= hidden_field_tag :pathname, user_path %>

  <%# jsで画面表示を変更する用%>
  <% if accessed_user_logged_in?(@user)%>
    <%= hidden_field_tag :accessed_user_logged_in_flg, "0" %>
  <% else %>
    <%= hidden_field_tag :accessed_user_logged_in_flg, "1" %>
  <% end %>

  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <h1>
          <%= link_to @user.name, user_show_detail_path, remote: true %>
        </h1>
      </section>
    </aside>
    <div class="col-md-8">
    </div>
  </div>
  <div id="user-modal" class="modal fade" tabindex="-1"></div>
  <div id="calendar"></div>
  <%= render "activity_histories/act_history_input_modal" %>
</div>

app/views/users/show_detail.js.erb
$("#user-modal").html("<%= escape_javascript(render 'user_modal') %>");
$("#user-modal").modal("show");