config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get    '/contact',        to:  'static_pages#contact'
  post   '/users/new',      to:  'users#create'
  get    '/terms',          to:  'static_pages#terms'
  get    '/privacy',        to:  'static_pages#privacy'
  get    '/login',          to:  'sessions#new'
  post   '/login',          to:  'sessions#create'
  delete '/logout',         to:  'sessions#destroy'
  get    '/users/:id/show_detail',          to:  'users#show_detail', as: 'user_show_detail'
  post   '/users/:id/act_histories/new',    to:  'activity_histories#create'
  get    '/users/:id/act_histories',        to:  'activity_histories#show'
  patch  '/users/:id/act_history',          to:  'activity_histories#update'
  delete '/users/:id/act_history',          to:  'activity_histories#destroy'
  post   '/users/:id/act_history/edit',     to:  'activity_histories#edit'
  resources :users
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul class="ul-left">
      <li>Applicationバージョン：v1.0.0</li>
    </ul>
    <ul class="ul-right">
      <li><%= link_to "利用規約", terms_path %></li>
      <li><%= link_to "プライバシーポリシー", privacy_path %></li>
      <li><%= link_to "お問い合わせ", contact_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header id="headernav">
  <nav class="navbar navbar-fixed-top navbar-default navbar-inverse">
    <div class="container">
      <%= link_to app_name, '/', id: "logo" %>
      <ul class="nav navbar-nav navbar-right ">
        <li><%= link_to "#{app_name}とは", '/#about'%></li>
        <li><%= link_to "お問い合わせ", contact_path %></li>
        <% if logged_in? %>
          <li><%= link_to "ユーザー一覧", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= current_user.name %> <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "ユーザーホーム", user_path(current_user) %></li>
              <li><%= link_to "ユーザー情報変更", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "ログアウト", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "ユーザー新規登録", new_user_path %></li>
          <li><%= link_to "ログイン", login_path %></li>
        <% end %>
      </ul>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- アイコン用 -->
    <link href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" rel="stylesheet">

  </head>
  <body>
    <%= render 'layouts/header' %>
    <% flash.each do |message_type, message| %>
      <%= content_tag(:div, message, class: "alert alert-#{message_type}", style:"margin-top:30px;") %>
    <% end %>
    <%= yield %>
    <div class="container">
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development?%>
    </div>
  </body>
</html>